version: '3.8'

services:
    projekt-zespolowy:
      build:
        context: ../
        dockerfile: docker/Dockerfile
      image: projekt-zespolowy:latest
      ports:
       - "8080:8080"
       - "8081:8081"
      depends_on:
       - sqlserver
      environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PZ;User Id=sa;Password=BazaDanych123!;TrustServerCertificate=True;MultipleActiveResultSets=true 
      networks:
       - projektzespolowynetwork
      restart: on-failure

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          SA_PASSWORD: "BazaDanych123!"
          ACCEPT_EULA: "Y"
        ports:
         - "1433:1433"
        networks:
         - projektzespolowynetwork
        volumes:
         - sqlvolume:/var/opt/mssql

networks:
  projektzespolowynetwork:

volumes:
  sqlvolume:

