version: '3.8'

services:
    projekt-zespolowy:
      build:
        context: ../
        dockerfile: docker/Dockerfile
      image: projekt-zespolowy:latest
      ports:
       - "8080:8080"
      depends_on:
       - sqlserver
      environment:
       - ASPNETCORE_ENVIRONMENT=Development
       - ConnectionStrings__DefaultConnection=Server=sqlserver,1433;Database=PZ;User Id=sa;Password=${{ secrets.DB_PASSWORD }};TrustServerCertificate=True;MultipleActiveResultSets=true
      networks:
       - projektzespolowynetwork
      restart: always

    sqlserver:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
          SA_PASSWORD: "${{ secrets.DB_PASSWORD }}"
          ACCEPT_EULA: "Y"
        ports:
         - "1433:1433"
        networks:
         - projektzespolowynetwork
        volumes:
         - ./init.sql:/init-db/init.sql
         - sqlvolume:/var/opt/mssql
        command: >
          bash -c "
            /opt/mssql/bin/sqlservr & 
            pid=$!;
            sleep 20;
            /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'BazaDanych123!' -i /init-db/init.sql -N -C;
            wait $pid
          "
        restart: always


    frontend:
        build:
          context: ../
          dockerfile: docker/Dockerfile.frontend.prod
        container_name: projekt-zespolowy-frontend
        ports:
          - "5173:80"
        depends_on:
          - projekt-zespolowy
        environment:
          - VITE_APP_API_URL=/api
        networks:
          - projektzespolowynetwork
        restart: always

networks:
  projektzespolowynetwork:

volumes:
  sqlvolume:

