FROM node:20-alpine AS build
WORKDIR /app


COPY frontend/package*.json ./

RUN npm install


COPY frontend/. ./
RUN rm -f .env
COPY ../docker/env2 .env
RUN npm run build


FROM nginx:alpine
WORKDIR /usr/share/nginx/html


COPY ../docker/nginx.conf /etc/nginx/nginx.conf


COPY --from=build /app/dist ./

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]