FROM node:20
WORKDIR /app
EXPOSE 5173

COPY frontend/package.json ./
COPY frontend/package-lock.json* ./

RUN npm install

COPY frontend/. ./

CMD ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]